import Head from 'next/head'
import Header from "../src/components/Header.js";

function About() {
    return(
    <>
    <Head>
      <title>About us</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <Header />
    <div className="w-full pt-4">
        <h1 className="text-4xl	text-center">About us</h1>
    </div>
    </>
    )
  }
  
  export default About