import Head from 'next/head'
import Header from "../src/components/Header.js";

function Careers() {
    return(
        <>
        <Head>
        <title>Careers</title>
        <meta name="description" content="Generated by create next app" />
        </Head>
        <Header />
        <div className="w-full pt-4">
        <h1 className="text-4xl	text-center">Careers</h1>
        </div>
      </>
    )
  }
  
  export default Careers