import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Header from "../src/components/Header.js";
import logo from '../src/components/tatadigital1.png';
// import Link from 'next/link';
//import anime from 'animejs/lib/anime.es.js';

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        </Head>
        <Header />
        <div className="w-full pt-4">
        <div className="flex items-center flex-col justify-center h-[700px] relative">
          <div className="mb-8">
                <span className="flex mr-3 w-[8rem] pt-1">
               <Image src={logo} alt="Tata Digital"/>
               </span>
    
          </div>
        <h1 className="text-4xl	text-center w-[280px] text-fuchsia-500">Making every day better
        </h1>
        <div className="bg-purple-500 w-[200px] h-[200px] absolute top-0	left-0"></div>
        <div className="bg-purple-300 w-[200px] h-[200px] absolute top-0	right-0"></div>
        <div className="bg-blue-300 w-[100px] h-[100px] absolute top-0	right-0 left-0 m-auto	top-10"></div>
        <div className="bg-gray-400 w-[150px] h-[150px] absolute right-0 bottom-0"></div>
        <div className="bg-blue-700 w-[100px] h-[100px] absolute	right-0 left-0 m-auto	bottom-0"></div>
        <div className="bg-green-300 w-[200px] h-[200px] absolute	left-20 bottom-10"></div>
        </div>
        
    </div>
    </>
     
  
  )
}
